# Generated by Django 5.2.4 on 2025-07-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex_code', models.CharField(max_length=7, unique=True)),
                ('r', models.PositiveSmallIntegerField()),
                ('g', models.PositiveSmallIntegerField()),
                ('b', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('times_discovered', models.PositiveIntegerField(default=1)),
            ],
            options={
                'indexes': [models.Index(fields=['-created_at'], name='colors_colo_created_5b6db4_idx'), models.Index(fields=['-times_discovered'], name='colors_colo_times_d_a57b55_idx')],
            },
        ),
    ]
